# Site title and subtitle. This is used in _includes/header.html
title: 'MarketingCloudSDK iOS (v6.2.0)'

propagationDelay: '5 minutes'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
# what do these mean these days?
google_analytics_id: 'UA-82902574-4' #PROD
#google_analytics_id: 'UA-82902574-1' #DocPreview
#google_analytics_id: 'UA-82902574-3' #PROD
#google_analytics_id: 'UA-82902574-2' #DocPreview

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/salesforce-marketingcloud/MarketingCloudSDK-iOS'

# Default categories (in order) to appear in the navigation
sections: [
    ['overview', 'Overview'],
    ['get-started', 'Get Started'],
    ['provisioning', 'Provisioning'],
    ['create-apps', 'Create Cloud Apps'],
    ['sdk-implementation', 'SDK Implementation'],
    ['push-notifications', 'Push Notifications'],
    ['application-badging', 'Application Badging'],
    ['location', 'Location Services'],
    ['inbox', 'Inbox'],
    ['analytics', 'Analytics'],
    ['opendirect', 'OpenDirect'],
    ['features', 'Feature Implementation'],
    ['user-data', 'User Data'],
    ['trouble', 'Troubleshooting'],
    ['upgrading', 'Upgrading'],
    ['resources', 'Additional Resources']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
#baseurl: "/JB4A-SDK-iOS" # the subpath of your site, e.g. /blog/
url: "http://salesforce-marketingcloud.github.io" # the base hostname & protocol for your site

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown

# Current SDK version, use for all mentions
currentVersion: "6.2.0"

